"""initial migration

Revision ID: 23804958e318
Revises: 54131f8c72d4
Create Date: 2020-04-09 14:59:07.335532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23804958e318'
down_revision = '54131f8c72d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('type_of_animal', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animals', 'type_of_animal')
    # ### end Alembic commands ###
