"""initial migration

Revision ID: 54131f8c72d4
Revises: 
Create Date: 2020-04-09 13:32:48.035082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54131f8c72d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###
